---
- name: Install packages for BeeGFS metadata server
  package:
    name: beegfs-meta
    state: "{{ beegfs_package_action }}"
  become: true
  notify: Restart BeeGFS meta service

- name: check directory for BeeGFS metadata
  stat:
  path: {{ beegfs_meta_path }}"
  register: meta_dir
- ansible.builtin.assert:
    that: meta_dir.stat.exists
    fail_msg: "'beegfs_meta_path' must exist and have the underlying filesystem mounted"
- ansible.builtin.meta:  end_play
  when: not meta_dir.stat.exists

- name: Specify connInterfacesFile
  lineinfile:
    path: /etc/beegfs/beegfs-meta.conf
    regexp: "^connInterfacesFile"
    line: "connInterfacesFile           = /etc/beegfs/connInterfacesFile"
  become: true
  notify: Restart BeeGFS meta service
...
