---
- name: Install packages for BeeGFS object storage server
  package:
    name: beegfs-storage
    state: "{{ beegfs_package_action }}"
  become: true
  notify: Restart BeeGFS storage service

- name: Create a list of devices that are mounted
  set_fact:
    mounted_devs: "{{ ansible_mounts | map(attribute='device') | list }}"

- name: Create storage config dirs
  file:
    path: "/etc/beegfs/{{ oss_port }}.d/"
    state: directory
  become: true
  notify: Restart BeeGFS storage service

- name: Add template beegfs-storage conf
  copy:
    src: "/etc/beegfs/beegfs-storage.conf"
    dest: "/etc/beegfs/{{ oss_port }}.d/beegfs-storage.conf"
    remote_src: true
    force: false
  become: true
  notify: Restart BeeGFS storage service

- name: Prepare storage devices
  block:
    - name: Stat the OSS device
      stat:
        path: "{{ oss_dev }}"
      register: oss_dev_stat
    - name: Fail if OSS device does not exist
      fail:
        msg: OSS device {{ oss_dev }} does not exist
      when: not oss_dev_stat.exists
    - name: check directory for BeeGFS metadata
      stat:
        path: {{ oss_path }}"
        register: oss_dir
    - ansible.builtin.assert:
        that: oss_dir.stat.exists
        fail_msg: "'oss_path' must exist and have the underlying filesystem mounted"
   - ansible.builtin.meta:  end_play
       when: not oss_dir.stat.exists
  become: true
  when: oss_dev_is_defined

  #/opt/beegfs/sbin/beegfs-setup-storage -f \
  #   -p {{ oss_path }} {{ oss_replace }} \
  #  -m {{ beegfs_mgmt_host }} \
  #  -c /etc/beegfs/{{ oss_port }}.d/beegfs-storage.conf \
  #  -S {{ inventory_hostname }}-{{ oss_port }} \
  #args:
  #  creates: "{{ oss_path }}/originalNodeID"
  #become: true
  #notify: Restart BeeGFS storage service

- name: set TCP storage port
  lineinfile:
    path: "/etc/beegfs/{{ oss_port }}.d/beegfs-storage.conf"
    regexp: '^connStoragePortTCP'
    line: "connStoragePortTCP = {{ oss_port }}"
  become: true
  notify: Restart BeeGFS storage service

- name: set UDP storage port
  lineinfile:
    path: "/etc/beegfs/{{ oss_port }}.d/beegfs-storage.conf"
    regexp: '^connStoragePortUDP'
    line: "connStoragePortUDP = {{ oss_port }}"
  become: true
  notify: Restart BeeGFS storage service

- name: Specify connInterfacesFile
  lineinfile:
    path: "/etc/beegfs/{{ oss_port }}.d/beegfs-storage.conf"
    regexp: "^connInterfacesFile"
    line: "connInterfacesFile           = /etc/beegfs/connInterfacesFile"
  become: true
  notify: Restart BeeGFS storage service
...
